// Auto-generated by Supabase CLI. Do not edit manually.
// Regenerate with: supabase gen types typescript --local > types/database.ts
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
  }
}
